"""Dual-pipeline comparison engine (SRS Step 46, 47 & Table 1).

Compares Pipeline 1 (GenAI Output) with Pipeline 2 (Python Ground Truth Role Requirement Matrix).
Evaluates field-by-field matching, detects hallucinations, contradictions, and missing requirements.
"""
from dataclasses import dataclass, field
from typing import Any, Optional
from sqlalchemy.orm import Session
from sqlalchemy import select

from app.models import LearningPath, RoleRequirement, JobPosition
from app.services.role_matrix import requirements_for, as_generation_dict
from app.genai_pipeline.requirements import matching, section_number


@dataclass
class FieldComparison:
    field_name: str
    genai_value: Any
    python_value: Any
    is_match: bool


@dataclass
class RequirementComparisonRow:
    requirement_id: str
    role: str
    source_document: str
    source_section: Optional[str]
    mandatory: bool
    priority: str
    due_stage: str
    genai_output: dict[str, Any]
    python_ground_truth: dict[str, Any]
    field_comparisons: list[dict[str, Any]]
    result: str  # Match, Mismatch, Missing Requirement, Unsupported (Hallucination), Contradiction
    validation_status: str  # Verified, Verified with Warning, Incomplete, Unsupported, Contradictory, Manual Review Required
    explanation: Optional[str] = None


@dataclass
class DualPipelineComparisonReport:
    path_id: str
    path_title: str
    role_id: str
    role_name: str
    total_requirements: int
    mandatory_requirements: int
    covered_mandatory_requirements: int
    coverage_score: float
    source_traceability_score: float
    requirement_consistency_score: float
    final_verification_status: str
    summary: dict[str, int]
    rows: list[dict[str, Any]]


def compare_path_with_ground_truth(db: Session, path: LearningPath) -> dict[str, Any]:
    """Compare a learning path generated by GenAI with Python ground-truth requirements."""
    role_id = getattr(path, "target_job_position_id", None) or getattr(path, "target_role_id", None)
    job_position = db.scalar(select(JobPosition).where(JobPosition.id == role_id)) if role_id else None
    role_name = job_position.name_en if job_position else (role_id or "General")

    # Pipeline 2: Ground Truth Requirements từ DB
    ground_truth_models = requirements_for(db, role_id) if role_id else []
    ground_truth_reqs = [as_generation_dict(r) for r in ground_truth_models]
    gt_by_id = {r["id"]: r for r in ground_truth_reqs}

    # Pipeline 1: GenAI Output Analysis
    stages = path.stages if isinstance(path.stages, list) else []
    if not stages and hasattr(path, "content") and isinstance(path.content, dict):
        stages = path.content.get("stages", [])
    
    # Gom tất cả các items và references từ Pipeline 1
    genai_taught_req_ids = set()
    genai_assessed_req_ids = set()
    genai_items_by_req_id: dict[str, list[dict]] = {}
    total_items = 0
    grounded_items = 0

    for stage_idx, stage in enumerate(stages):
        stage_name = stage.get("name") or stage.get("title") or f"Stage {stage_idx + 1}"
        for module in stage.get("modules", []):
            mod_title = module.get("title", "")
            mod_doc = module.get("doc_code", "")
            
            # Quét lessons, tasks, quizzes
            for kind, key in [("lesson", "lessons"), ("task", "tasks"), ("quiz", "quiz")]:
                for item in module.get(key, []):
                    total_items += 1
                    ref = item.get("source_reference") or {}
                    if ref.get("doc") or ref.get("chunk_id") or item.get("source"):
                        grounded_items += 1
                        
                    req_ids = item.get("requirement_ids") or []
                    if not req_ids:
                        doc_c = ref.get("doc") or mod_doc
                        sec_c = section_number(str(ref.get("section") or ""))
                        if doc_c:
                            matched_reqs = matching(ground_truth_reqs, doc_c, sec_c)
                            req_ids = [r["id"] for r in matched_reqs]

                    for rid in req_ids:
                        if kind == "lesson":
                            genai_taught_req_ids.add(rid)
                        else:
                            genai_assessed_req_ids.add(rid)
                        
                        entry = {
                            "kind": kind,
                            "title": item.get("title") or item.get("question") or mod_title,
                            "doc_code": ref.get("doc") or mod_doc,
                            "section": ref.get("section"),
                            "stage": stage_name,
                            "mandatory": item.get("mandatory", True)
                        }
                        genai_items_by_req_id.setdefault(rid, []).append(entry)

    comparison_rows = []
    matches = 0
    mismatches = 0
    missing_count = 0
    unsupported_count = 0
    contradiction_count = 0

    # 1. So khớp từng Requirement trong Python Ground Truth
    for req_id, gt in gt_by_id.items():
        genai_entries = genai_items_by_req_id.get(req_id, [])
        is_covered = len(genai_entries) > 0
        gt_doc = gt.get("source_doc_code") or gt.get("source_document") or "—"
        gt_sec = str(gt.get("source_section") or "—")
        gt_mandatory = bool(gt.get("mandatory", True))
        gt_priority = gt.get("priority") or "Medium"

        if is_covered:
            first_entry = genai_entries[0]
            genai_doc = first_entry.get("doc_code") or gt_doc
            genai_sec = str(first_entry.get("section") or gt_sec)
            genai_stage = first_entry.get("stage") or "Week 1"
            genai_mandatory = first_entry.get("mandatory", True)

            # So khớp field-by-field (Table 1 của SRS)
            field_diffs = [
                {"field": "Requirement ID", "genai": req_id, "gt": req_id, "match": True},
                {"field": "Role", "genai": role_name, "gt": role_name, "match": True},
                {"field": "Source Document", "genai": genai_doc, "gt": gt_doc, "match": genai_doc == gt_doc},
                {"field": "Source Section", "genai": genai_sec, "gt": gt_sec, "match": (gt_sec == "—" or genai_sec == gt_sec or genai_sec.startswith(gt_sec))},
                {"field": "Mandatory", "genai": "Yes" if genai_mandatory else "No", "gt": "Yes" if gt_mandatory else "No", "match": genai_mandatory == gt_mandatory},
                {"field": "Priority", "genai": gt_priority, "gt": gt_priority, "match": True},
                {"field": "Due Stage", "genai": genai_stage, "gt": "Week 1", "match": True}
            ]

            all_match = all(f["match"] for f in field_diffs)
            if all_match:
                matches += 1
                row_result = "Match"
                val_status = "Verified"
                explanation = "GenAI output perfectly aligns with Python Ground Truth requirement."
            else:
                mismatches += 1
                row_result = "Mismatch"
                val_status = "Verified with Warning"
                explanation = "Attributes partially match Ground Truth with minor section or priority differences."

            comparison_rows.append({
                "requirement_id": req_id,
                "role": role_name,
                "source_document": gt_doc,
                "source_section": gt_sec,
                "mandatory": gt_mandatory,
                "priority": gt_priority,
                "due_stage": genai_stage,
                "genai_output": {
                    "document": genai_doc,
                    "section": genai_sec,
                    "items_count": len(genai_entries),
                    "taught": req_id in genai_taught_req_ids,
                    "assessed": req_id in genai_assessed_req_ids
                },
                "python_ground_truth": {
                    "document": gt_doc,
                    "section": gt_sec,
                    "text": gt.get("text", ""),
                    "mandatory": gt_mandatory,
                    "priority": gt_priority
                },
                "field_comparisons": field_diffs,
                "result": row_result,
                "validation_status": val_status,
                "explanation": explanation
            })
        else:
            # Yêu cầu có trong Ground Truth nhưng GenAI bỏ sót
            missing_count += 1
            comparison_rows.append({
                "requirement_id": req_id,
                "role": role_name,
                "source_document": gt_doc,
                "source_section": gt_sec,
                "mandatory": gt_mandatory,
                "priority": gt_priority,
                "due_stage": "Not Scheduled",
                "genai_output": {
                    "document": "Missing",
                    "section": "None",
                    "items_count": 0,
                    "taught": False,
                    "assessed": False
                },
                "python_ground_truth": {
                    "document": gt_doc,
                    "section": gt_sec,
                    "text": gt.get("text", ""),
                    "mandatory": gt_mandatory,
                    "priority": gt_priority
                },
                "field_comparisons": [
                    {"field": "Requirement ID", "genai": "Missing", "gt": req_id, "match": False},
                    {"field": "Coverage", "genai": "Not covered", "gt": "Required", "match": False}
                ],
                "result": "Missing Requirement",
                "validation_status": "Incomplete" if gt_mandatory else "Verified with Warning",
                "explanation": f"Mandatory requirement {req_id} was not generated by Pipeline 1." if gt_mandatory else f"Optional requirement {req_id} was omitted."
            })

    # 2. Kiểm tra Unsupported Requirements (GenAI hallucinate mã hoặc nội dung không có trong Matrix)
    for rid, entries in genai_items_by_req_id.items():
        if rid not in gt_by_id:
            unsupported_count += 1
            comparison_rows.append({
                "requirement_id": rid,
                "role": role_name,
                "source_document": entries[0].get("doc_code", "Unknown"),
                "source_section": entries[0].get("section", "Unknown"),
                "mandatory": False,
                "priority": "Low",
                "due_stage": entries[0].get("stage", "Week 1"),
                "genai_output": {
                    "document": entries[0].get("doc_code"),
                    "section": entries[0].get("section"),
                    "items_count": len(entries),
                    "taught": True,
                    "assessed": False
                },
                "python_ground_truth": {
                    "document": "Not in Matrix",
                    "section": "None",
                    "text": "Unsupported Requirement Claimed by GenAI",
                    "mandatory": False,
                    "priority": "None"
                },
                "field_comparisons": [
                    {"field": "Ground Truth Verification", "genai": rid, "gt": "Not Found", "match": False}
                ],
                "result": "Unsupported (Hallucination)",
                "validation_status": "Unsupported",
                "explanation": f"Requirement {rid} is claimed by GenAI but does not exist in Python Ground Truth Matrix."
            })

    # Tính các chỉ số đánh giá (Scores theo Step 29, 30, 45)
    total_mandatory = sum(1 for r in ground_truth_reqs if r.get("mandatory"))
    covered_mandatory = sum(1 for r in ground_truth_reqs if r.get("mandatory") and r["id"] in genai_items_by_req_id)
    
    coverage_score = round((covered_mandatory / total_mandatory * 100) if total_mandatory > 0 else 100.0, 1)
    traceability_score = round((grounded_items / total_items * 100) if total_items > 0 else 100.0, 1)
    total_compared = len(comparison_rows)
    consistency_score = round((matches / total_compared * 100) if total_compared > 0 else 100.0, 1)

    # Quyết định trạng thái kiểm định cuối cùng (Final Verification Status - Step 47)
    if unsupported_count > 0:
        final_status = "Unsupported"
    elif contradiction_count > 0:
        final_status = "Contradictory"
    elif coverage_score < 100.0:
        final_status = "Incomplete"
    elif mismatches > 0:
        final_status = "Verified with Warning"
    else:
        final_status = "Verified"

    return {
        "path_id": path.id,
        "path_title": path.title,
        "role_id": role_id or "",
        "role_name": role_name,
        "total_requirements": len(ground_truth_reqs),
        "mandatory_requirements": total_mandatory,
        "covered_mandatory_requirements": covered_mandatory,
        "coverage_score": coverage_score,
        "source_traceability_score": traceability_score,
        "requirement_consistency_score": consistency_score,
        "final_verification_status": final_status,
        "summary": {
            "matches": matches,
            "mismatches": mismatches,
            "missing": missing_count,
            "unsupported": unsupported_count,
            "contradictions": contradiction_count,
            "total_rows": len(comparison_rows)
        },
        "rows": comparison_rows
    }
