from pydantic import BaseModel, Field


class SourceCitation(BaseModel):
    """Grounding metadata citing the exact location in the source document."""
    doc_id: str = Field(description="Document ID hash from source file")
    source_file: str = Field(description="Original file name")
    page_number: int = Field(description="Page number where this information is found")
    section_heading: str = Field(description="Heading or section name referenced")
    exact_quote: str = Field(description="Direct quotation or sentence from source text")


class QuizQuestionSchema(BaseModel):
    """Multiple choice question to assess understanding of policy material."""
    question_id: str = Field(description="Unique question identifier, e.g. Q1")
    question_text: str = Field(description="The quiz question text")
    options: list[str] = Field(description="List of 4 answer options (e.g. ['A. ...', 'B. ...'])")
    correct_answer: str = Field(description="Correct option identifier, e.g. 'A' or exact option string")
    explanation: str = Field(description="Explanation of why this answer is correct based on the policy")
    source_citation: SourceCitation = Field(description="Source citation grounding this question")


class TaskSchema(BaseModel):
    """Individual action item or learning step within a training module."""
    task_id: str = Field(description="Task identifier, e.g. T1.1")
    title: str = Field(description="Actionable title for the task")
    description: str = Field(description="Clear instructions on what employee needs to do")
    estimated_minutes: int = Field(description="Estimated time in minutes to complete")
    source_citation: SourceCitation = Field(description="Source citation grounding this task")


class ModuleSchema(BaseModel):
    """Structured training module containing tasks and knowledge checks."""
    module_id: str = Field(description="Module identifier, e.g. M1")
    title: str = Field(description="Module title")
    description: str = Field(description="Summary of topics covered in this module")
    order_index: int = Field(description="Sequential order of the module, starting at 1")
    tasks: list[TaskSchema] = Field(description="List of tasks in this module")
    quizzes: list[QuizQuestionSchema] = Field(description="Quizzes to assess understanding")
    source_citation: SourceCitation = Field(description="Source citation grounding this module")


class OnboardingPlanSchema(BaseModel):
    """Complete role-specific onboarding plan generated by Pipeline 1."""
    plan_id: str = Field(description="Unique plan ID, e.g. PLAN-SEC-01")
    target_role: str = Field(description="Job role for which this onboarding plan is designed")
    title: str = Field(description="Plan title")
    summary: str = Field(description="Overview of the onboarding plan")
    prompt_version: str = Field(description="Version of the prompt template used")
    modules: list[ModuleSchema] = Field(description="List of structured modules")
    source_citation: SourceCitation = Field(description="Primary document source citation for the overall plan")
