from logging.config import fileConfig

from alembic import context
from alembic.operations import ops
from sqlalchemy import CheckConstraint, Column, Enum
from sqlalchemy.sql.elements import conv

import app.models  # noqa: F401  registers every table on Base.metadata for autogenerate
from app.core.config import get_settings
from app.db.base import Base
from app.db.session import build_engine

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata

# Tests pass their own URL via `sqlalchemy.url`; everything else uses DATABASE_URL.
database_url = config.get_main_option("sqlalchemy.url") or get_settings().database_url
is_sqlite = database_url.startswith("sqlite")


def _drop_duplicate_enum_checks(_context, _revision, directives) -> None:
    """Keep one CHECK per enum column in autogenerated CREATE TABLE ops.

    For `Enum(create_constraint=True)` autogenerate emits the CHECK three times: inside `sa.Enum`,
    once under the enum name and once under the naming-convention name. Only the last one is kept
    so constraint names stay predictable for later migrations.
    """
    script = directives[0]
    for upgrade_ops in script.upgrade_ops_list:
        for op in upgrade_ops.ops:
            if not isinstance(op, ops.CreateTableOp):
                continue
            enum_names = set()
            for column in op.columns:
                if isinstance(column, Column) and isinstance(column.type, Enum) and not column.type.native_enum:
                    enum_names.add(column.type.name)
                    column.type.create_constraint = False
            op.columns = [
                item for item in op.columns
                if not (isinstance(item, CheckConstraint) and not isinstance(item.name, conv) and item.name in enum_names)
            ]


def run_migrations_offline() -> None:
    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=is_sqlite,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = build_engine(database_url)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # SQLite cannot ALTER most constraints; batch mode rebuilds the table instead.
            render_as_batch=is_sqlite,
            compare_type=True,
            process_revision_directives=_drop_duplicate_enum_checks,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
